# This is a basic workflow to help you get started with Actions

name: Auto-Update Data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 9-15 * * *'
    - cron: '*/5 16-18 * * *'
    - cron: '*/20 19-21 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.2

      - name: Install pup
        run: go get github.com/ericchiang/pup
      
      - name: Set up Git
        run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"

      - name: Debug
        run: |
          export GOPATH=$(go env GOPATH)
          ls $GOPATH/bin

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          ./update.sh
